version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coveragee
          command: npm run test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
